#!/bin/sh

SERVICE="$1"
ACTION="$2"

usage() {
	echo "usage: service <name> <start|stop>"
	echo "       start or stop a given service (init script)"
	echo
	exit 1
}

case "$ACTION" in
	start|stop) ;;
	*) usage;;
esac

for i in /opt/*/etc/init.d/$SERVICE /etc/init.d/$SERVICE; do
	if [ -x "$i" ]; then
		echo "running $i $ACTION"
		"$i" "$ACTION"
		exit $?
	fi
done

echo "$SERVICE not found in /etc/init.d/ and /opt/*/etc/init.d/"
exit 1
