#!/bin/sh
im()
{
	modname=$1
	# only "options" parameter is supported in modprobe.conf
	# if you want more, you should probably use real modprobe
	params=$(sed -n "/^options $modname/{
				s/^options $modname\s\(.*\)\$/\1/;
				p
			}" /etc/modprobe.conf 2>/dev/null)
	shift
	/sbin/insmod /lib/modules/2.6.26.8-nevis/${modname}.ko ${params:-$@}
}

case $1 in
start)
	im cs_frontpanel
	im cifs
	im fuse
	im usbserial
	im ftdi_sio
	im cnxt_i2c
	im cnxt_kal
	im cnxt_base init=0
	im cnxt_fb cnxtfb_standalone=1 cnxtfb_width=1280 cnxtfb_height=720
	im cnxt_lnx
	im cnxt_alsa
	im cs_control
	im stv6110 verbose=0
	im stv090x verbose=0
	im tda10023
	im dvb-core
	im cs_frontend
	im cnxt_sata_drv
	;;
esac
