#!/bin/sh

# manage network interfaces and configure some networking options

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case "$1" in
    start)
	echo -n "Configuring network interfaces... "
	ifup -a
	echo "done."
	;;
    stop)
	echo -n "Deconfiguring network interfaces... "
	ifdown -a
	echo "done."
	;;
    force-reload|restart)
	echo -n "Reconfiguring network interfaces... "
	ifdown -a
	ifup -a &
	echo "done."
	;;
esac

exit 0

