#!/bin/sh

# manage network interfaces and configure some networking options

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case "$1" in
    start)
	echo -n "Configuring network interfaces... "
	grep -q '^auto lo' /etc/network/interfaces && sed -i '/^auto lo/d' /etc/network/interfaces
	ifup lo 2>/dev/null
    	touch /tmp/.init_networking
    	(
		ifup -a
		rm /tmp/.init_networking
	) &
	echo "done (continuing in background)."
	;;
    stop)
	echo -n "Deconfiguring network interfaces... "
	ifdown -a
	echo "done."
	;;
    force-reload|restart)
	echo "Reconfiguring network interfaces... "
	ifdown -a
	ifup -a
	echo "...done."
	;;
esac

exit 0

