#!/bin/sh

. /etc/profile


while [ '/tmp/.init_*' != "`echo /tmp/.init_*`" ] ; do
	usleep 100000
done

if [ -e /etc/init.d/start_neutrino ]; then
	exec /etc/init.d/start_neutrino
elif [ -e /etc/init.d/start_enigma ]; then
	exec /etc/init.d/start_enigma
else
	echo "Neither start_neutrino nor start_enigma found"
fi
