#!/bin/sh

im()
{
	modname=$1
	modsane=${1//-/_}
	params=$(eval echo \$OPT_${modsane})
	shift
	file=/lib/modules/${KVER}/${modname}.ko
	# the CS modules are in /lib/modules/$KVER/*,
	# own built modules are in /lib/modules/$KVER/kernel/... subdirectories
	if test -e $file; then
		/sbin/insmod $file ${params:-$@}
	else
		/sbin/modprobe $modname $@
	fi
}

case $1 in
start)
	read dummy dummy KVER dummy < /proc/version
	# set all "option foo ..." as OPT_foo="..." variables
	eval $(sed -n "/^options\s/{
		s/^options\s\(\S\+\)\s\(.*\)\$/OPT_\1=\"\2\"/;
		s/^\(\S\+\)-/\1_/g;
		s/^\(\S\+\)-/\1_/g;
		s/^\(\S\+\)-/\1_/g;
		p }" /etc/modprobe.conf)
	im cs_frontpanel
	im cifs
	im fuse
	im usbserial
	im ftdi_sio
	im cnxt_i2c
	im cnxt_kal
	im cnxt_base init=0
	im cnxt_fb cnxtfb_standalone=1 cnxtfb_width=1280 cnxtfb_height=720
	im cnxt_lnx
	im cnxt_alsa
	im cs_control
	im stv6110 verbose=0
	im stv090x verbose=0
	im tda10023
	im dvb-core
	im cs_frontend
	im cnxt_sata_drv
	;;
esac
