#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
export TZ=`cat /etc/TZ`
# the default "vt102" is crap.
export TERM=linux
#
# reset colors, to not hurt my eyes...
echo -e "\033[0m"

# for next boot ;)
[ -e /dev/console ] || mknod -m 644 /dev/console c 5 1
mount /proc
mount /dev
# make sure that important devices are there before mdev startup
# otherwise a redirection in a mdev script might create them...
mknod -m 644 /dev/console	c 5 1
mknod -m 666 /dev/null		c 1 3
mount /sys
mount /tmp
mkdir /dev/pts
mkdir -p /dev/shm/usb
# directory for mounting disks
mkdir /tmp/media
rm -f /media		# don't remove if it is a directory
ln -s /tmp/media /	# /media points to /tmp/media/
#
# make mdev try to process the events in sequential order
echo >/dev/mdev.seq
# start up mdev with coldplugging
mdev -s
# manually create nodes for crappy drivers
/sbin/mknodes
# register mdev as hotplug handler
echo $(which mdev) > /proc/sys/kernel/hotplug

dmesg -n 4
# update library cache before running init scripts
ldconfig
# if ldconfig is not there, set up LD_LIBRARY_PATH
if test -e /etc/ld.so.conf -a ! -e /etc/ld.so.cache; then
	_tmp=$(cat /etc/ld.so.conf)
	if test "$_tmp"; then
		export LD_LIBRARY_PATH=${_tmp//[[:space:]]/:}
	fi
	unset _tmp
fi

. /etc/init.d/functions

run_initscripts start
