#!/bin/sh
L=/opt/common/lib
if ! grep -q ^$L /etc/ld.so.conf 2>/dev/null; then
	echo "adding $L to /etc/ld.so.conf"
	echo $L >> /etc/ld.so.conf
fi
if test -x /sbin/ldconfig; then
	echo "updating dynamic linker cache..."
	/sbin/ldconfig
fi
