#!/bin/sh
ETC=/opt/dropbear/etc/dropbear
BIN=/opt/dropbear/bin
for keytype in dss rsa; do
	keyfile=${ETC}/dropbear_${keytype}_host_key
	test -e $keyfile && continue
	${BIN}/dropbearkey -t $keytype -f $keyfile
done
