#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
export TZ=`cat /etc/TZ`
# the default "vt102" is crap.
export TERM=linux

mount -t proc proc /proc
mount -t devfs dev /dev
mount -t sysfs sys /sys
mount -t tmpfs tmp /tmp
mount -t devpts devpts /dev/pts
mount -t usbfs usbfs /proc/bus/usb
# directory for mounting disks
mkdir /tmp/media
rm -f /media		# don't remove if it is a directory
ln -s /tmp/media /	# /media points to /tmp/media/
# update library cache before running init scripts
ldconfig
# if ldconfig is not there, set up LD_LIBRARY_PATH
if test -e /etc/ld.so.conf -a ! -e /etc/ld.so.cache; then
	_tmp=$(cat /etc/ld.so.conf)
	if test "$_tmp"; then
		export LD_LIBRARY_PATH=${_tmp//[[:space:]]/:}
	fi
	unset _tmp
fi

. /etc/init.d/functions

run_initscripts start
