#!/bin/sh

case $1 in
start)
	# actually only mounts devpts with the default fstab...
	/bin/mount -a

	echo "Enable Swap space (if exist)..."
	/sbin/swapon -a > /dev/null 2>&1
	exit 0
	;;
stop)
	umount -a
	;;
esac
