#!/bin/sh

case $1 in
start)
	# actually only mounts devpts with the default fstab...
	/bin/mount -a
	if grep -q swap /etc/fstab; then # todo: better grep ;-)
		echo "Enable Swap space..."
		/sbin/swapon -a
	fi
	exit 0
	;;
stop)
	umount -a -r		# unmount, if busy remount readonly
	/sbin/swapoff -a	# so that swapping doesn't wake up the drive
	/sbin/hdparm -y /dev/sd*[^0-9]	# whole devices only, no partitions
	;;
esac
