#!/bin/sh

im()
{
	modname=$1
	modsane=${1//-/_}
	params=$(eval echo \$OPT_${modsane})
	shift
	file=/lib/modules/${KVER}/${modname}.ko
	# own built modules are in /lib/modules/$KVER/kernel/... subdirectories
	# ...but we can override this by putting modules to /lib/modules/$KVER directly
	if test -e $file; then
		echo "overriding ${modname}.ko from /lib/modules/$KVER ..."
		/sbin/insmod $file ${params:-$@}
	else
		/sbin/modprobe $modname $@
	fi
}

# hack, ugly: we should not need to know about neutrino.conf internals
get_vidmode()
{
	M=$(grep video_Mode= /var/tuxbox/config/neutrino.conf)
	if [ -z "$M" ]; then
		echo "1280x720-32@50"
		return
	fi
	M=${M#*=}
	if [ $M = 6 ] || [ $M -gt 7 ]; then
		echo "1920x1080-32@50"
		return
	fi
	if [ $M -lt 5 ]; then
		echo "720x576-32@50"
		return
	fi
	echo "1280x720-32@50"
}

case $1 in
start)
	read dummy dummy KVER dummy < /proc/version
	grep -q uinput /lib/modules/${KVER}/modules.dep || depmod -a
	# set all "option foo ..." as OPT_foo="..." variables
	eval $(sed -n "/^options\s/{
		s/^options\s\(\S\+\)\s\(.*\)\$/OPT_\1=\"\2\"/;
		s/^\(\S\+\)-/\1_/g;
		s/^\(\S\+\)-/\1_/g;
		s/^\(\S\+\)-/\1_/g;
		p }" /etc/modprobe.conf)
	im aotom
	echo loading > /dev/vfd
	im uinput
	im e2_proc
	im stmcore_display_sti7111
	MEMSIZE=12m	# neutrino now needs 12m for FB scaling backbuffer
	VM=$(get_vidmode)
	im stmfb.ko display0=$VM:$MEMSIZE:pal:yuv:yuv
	ustslave /dev/st231-1 /boot/audio.elf
	ustslave /dev/st231-0 /boot/video.elf
	im cpu_frequ
	im embxshell
	im embxmailbox mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
	im embxshm mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
	im mme_host transport0=shm
	im avs type=avs_pio
	im mmelog
	im ksound
	im p2div64
	im stm_v4l2
	im stmvout
	im stmvbi
	im pseudocard
	im stv090x
	im pti waitMS=20 videoMem=4096
	im stm_monitor
	im stmsysfs
	im stmdvb
	im player2 discardlateframe=0
	im sth264pp
	im stmalloc
	im platform
	im silencegen
	im bpamem
	im smartcard
	[ -f /etc/modules.extra ] && eval `awk '{ if ($1) print "modprobe " $1 " " $2,$3,$4,$5,$6,$7,$8,$9 "; "}' < /etc/modules.extra`
	;;
esac
