#!/bin/sh
#
# Thomas FFTeam www.Familienforum.biz
#
cam_start() {
if [ -f /var/etc/.oscam ]; then
  /var/emu/oscam -b -c /var/keys >/dev/null
fi

if [ -f /var/etc/.osemu ]; then
  /var/emu/osemu -a emu:emu d -p 11000 -b -r 8001:17999 /var/keys >/dev/null
  sleep 2
  /var/emu/oscam -b -c /var/keys >/dev/null
fi

if [ -f /var/etc/.mgcamd ]; then
  /var/emu/mgcamd >/dev/null
fi

if [ -f /var/etc/.gbox ]; then
  /var/emu/gbox & > /dev/null 2>&1
fi

if [ -f /var/etc/.wicard ]; then
  ulimit -s 512
  /var/emu/wicard -c /var/keys/wicard.conf & > /dev/null
fi

if [ -f /var/etc/.camd3 ]; then
  /var/emu/camd3 /var/keys/camd3.config >/dev/null
fi
}

cam_stop() {
  touch /tmp/gbox.kill
  sleep 2
  rm -rf /tmp/*.info /tmp/mgcamd.pid /tmp/camd.socket /tmp/wicard.* /tmp/gbox.*  /tmp/share.* /tmp/*.log /tmp/*.txt
	sleep 2
  killall -9 mgcamd >/dev/null
  killall -9 oscam >/dev/null
  killall -9 osemu >/dev/null
  killall -9 gbox >/dev/null
  killall -9 cs2gbox >/dev/null
  killall -9 camd3 >/dev/null
  killall -9 cccam >/dev/null
  killall -9 wicard >/dev/null
}

case $1 in
start)
	cam_start
	;;
stop)
	cam_stop
	;;
restart)
	cam_stop
	sleep 1
	cam_start
	sleep 1
	/bin/pzapit -rz
	;;
init)
	sleep 1
	cam_start
	if [ "$REZAP" == 1 ]
	then
		sleep 5
		/bin/pzapit -rz
	fi
esac

