#!/bin/sh

. /etc/profile


while [ '/tmp/.init_*' != "`echo /tmp/.init_*`" ] ; do
	usleep 100000
done

if [ -e /etc/init.d/start_neutrino ]; then
	exec /etc/init.d/start_neutrino >/dev/kmsg 2>&1
elif [ -e /etc/init.d/start_enigma ]; then
	exec /etc/init.d/start_enigma >/dev/kmsg 2>&1
else
	echo "Neither start_neutrino nor start_enigma found" | tee > /dev/kmsg
fi
