#!/bin/sh
#
# /linuxrc script for USB booting
#
# (C) 2009 Stefan Seyfried, License: GPL V2
#
# this is a hack for booting the coolstream HD1 from USB
# put this script into the original root fs as /linuxrc,
# chmod it to 0755 and add "init=/linuxrc" to the bootargs of
# U-Boot
#
# the usb stick should have an "/oldroot" directory, so you
# can unmount the jffs2 "old" root later.
#
e="/bin/echo linuxrc:"

$e "***** linuxrc ******"
/bin/mkdir -p /tmp/newroot

$e mounting sda1...

if ! /bin/mount -n /dev/sda1 /tmp/newroot; then
	$e "mount failed, doing normal init. Goodbye!"
	exec /sbin/init
fi

if /bin/test -e /tmp/newroot/sbin/pivot_root; then
	$e "using pivot_root to enter new root"
	cd /tmp/newroot
	sbin/pivot_root . oldroot
	bin/mknod dev/console c 5 1
	exec sbin/chroot . sbin/init < dev/console > dev/console 2>&1
fi

$e "no /sbin/pivot_root on sda1, trying normal chroot"

if /bin/test -x /tmp/newroot/sbin/init; then
	exec /sbin/chroot /tmp/newroot /sbin/init
fi

$e "no /sbin/init on sda1, booting from flash."
exec /sbin/init
