#!/bin/sh
/bin/echo "running $0"
# <name ><type> <mode> <uid> <gid> <major> <minor> <start> <inc> <count>

makedevs /dev << EOF
# is this needed at all?
watchdog		c 644 0 0 10	130

cnxt			d 755 0 0

cnxt/cnxt_gen_drv	c 644 0 0 102	0
notifyq			c 644 0 0 102	1
user_kal		c 644 0 0 102	2
display			c 644 0 0 238	0
# newer drivers and libs
cs_control		c 644 0 0 249	0
# older drivers
cs_control_scart	c 644 0 0 250	0
cs_control_pwm		c 644 0 0 251	0
iolib			c 644 0 0 253	0

input			d 755 0 0
input/nevis_ir		c 644 0 0 240	0
input/event0_uinput	c 644 0 0 10	223
input/mouse		c 644 0 0 13	32	0 1 4
input/mice		c 644 0 0 13	63
input/event2		c 644 0 0 13	66
input/event3		c 644 0 0 13	67
EOF
ln -sf nevis_ir	/dev/input/event0
ln -sf nevis_ir	/dev/input/input0

/bin/echo "done $0"
